kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: fauria/vsftpd
      ports:
        - containerPort: 21
          name: "ftp-server"
      volumeMounts:
      - mountPath: "/home/vsftpd"
        name: task-pv-storage
